package GUI;

import Database.DB;
import Model.Save;
import Model.Validation;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import static javax.swing.BorderFactory.createTitledBorder;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;

public class AddSupplier extends javax.swing.JFrame {

    private int xMouse;
    private int yMouse;
    private Main menu;
    private Suppliers supplierView;

    public AddSupplier() {
        initComponents();
        generateID();
        
        jLabel5.setVisible(false);
        active.setVisible(false);
        inactive.setVisible(false);
    }

    public AddSupplier(Main me, Suppliers sup, boolean b) {
        this();
        this.menu = me;
        this.supplierView = sup;
        menu.setEnabled(false);
        
        if (b) {
            jLabel5.setVisible(false);
            active.setVisible(false);
            inactive.setVisible(false);
        } else {
            jLabel2.setText("Supplier");
            jLabel5.setVisible(true);
            active.setVisible(true);
            inactive.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        state = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        txt_company = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_mobile = new javax.swing.JTextField();
        txt_fax = new javax.swing.JTextField();
        txt_street = new javax.swing.JTextField();
        txt_city = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        id_supplier = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        active = new javax.swing.JRadioButton();
        inactive = new javax.swing.JRadioButton();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(225, 225, 225));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_fname.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_fname.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "First Name", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_fname.setOpaque(false);
        txt_fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_fnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_fnameFocusLost(evt);
            }
        });
        jPanel1.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 190, 50));

        txt_lname.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_lname.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Last Name", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_lname.setOpaque(false);
        txt_lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_lnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_lnameFocusLost(evt);
            }
        });
        jPanel1.add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 25, 190, 50));

        txt_nic.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_nic.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "N I C", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_nic.setOpaque(false);
        txt_nic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nicFocusLost(evt);
            }
        });
        txt_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nicKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 25, 190, 50));

        txt_company.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_company.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Company", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_company.setOpaque(false);
        txt_company.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_companyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_companyFocusLost(evt);
            }
        });
        jPanel1.add(txt_company, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 100, 740, 50));

        txt_email.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_email.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "E mail", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_email.setOpaque(false);
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 220, 190, 50));

        txt_mobile.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_mobile.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Phone No", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_mobile.setOpaque(false);
        txt_mobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_mobileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_mobileFocusLost(evt);
            }
        });
        txt_mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_mobileKeyTyped(evt);
            }
        });
        jPanel1.add(txt_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 190, 50));

        txt_fax.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_fax.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Fax No", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_fax.setOpaque(false);
        txt_fax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_faxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_faxFocusLost(evt);
            }
        });
        txt_fax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_faxKeyTyped(evt);
            }
        });
        jPanel1.add(txt_fax, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 220, 190, 50));

        txt_street.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_street.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Street", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_street.setOpaque(false);
        txt_street.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_streetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_streetFocusLost(evt);
            }
        });
        jPanel1.add(txt_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 340, 460, 50));

        txt_city.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        txt_city.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "City", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 15), new java.awt.Color(102, 102, 102))); // NOI18N
        txt_city.setOpaque(false);
        txt_city.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cityFocusLost(evt);
            }
        });
        txt_city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cityKeyTyped(evt);
            }
        });
        jPanel1.add(txt_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 340, 190, 50));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(84, 153, 199));
        jLabel4.setText(" Contact Details____________________________________________________________________________________________________");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 180, 740, 20));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(84, 153, 199));
        jLabel3.setText("  Address _________________________________________________________________________________________________________");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 300, 740, 20));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 780, 480));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_supplier.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        id_supplier.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Supplier ID", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel3.add(id_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 50));

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear1.png"))); // NOI18N
        btn_clear.setBorder(null);
        btn_clear.setBorderPainted(false);
        btn_clear.setContentAreaFilled(false);
        btn_clear.setFocusPainted(false);
        btn_clear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear2.png"))); // NOI18N
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel3.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 40));

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save1.png"))); // NOI18N
        btn_save.setBorder(null);
        btn_save.setBorderPainted(false);
        btn_save.setContentAreaFilled(false);
        btn_save.setFocusPainted(false);
        btn_save.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save2.png"))); // NOI18N
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel3.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 150, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Status");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 50, 20));

        active.setBackground(new java.awt.Color(255, 255, 255));
        state.add(active);
        active.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        active.setSelected(true);
        active.setText("   Active");
        active.setBorder(null);
        active.setContentAreaFilled(false);
        active.setFocusPainted(false);
        jPanel3.add(active, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, -1));

        inactive.setBackground(new java.awt.Color(255, 255, 255));
        state.add(inactive);
        inactive.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        inactive.setText("   Deactivate");
        inactive.setBorder(null);
        inactive.setContentAreaFilled(false);
        inactive.setFocusPainted(false);
        jPanel3.add(inactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 120, -1));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 190, 480));

        header.setBackground(new java.awt.Color(253, 253, 253));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(117, 113, 112));
        jLabel2.setText(" Add Supplier");
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit1.png"))); // NOI18N
        exit.setBorder(null);
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setFocusPainted(false);
        exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit2.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        header.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 25, 25));

        jPanel4.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 990, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        menu.setEnabled(true);
        supplierView.loadTableData();
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void txt_fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fnameFocusGained
        txt_fname.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "First Name", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_fnameFocusGained

    private void txt_fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fnameFocusLost
        txt_fname.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "First Name", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_fnameFocusLost

    private void txt_lnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lnameFocusGained
        txt_lname.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "Last Name", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_lnameFocusGained

    private void txt_lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lnameFocusLost
        txt_lname.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "Last Name", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_lnameFocusLost

    private void txt_nicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nicFocusGained
        txt_nic.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "N I C", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_nicFocusGained

    private void txt_nicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nicFocusLost
        txt_nic.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "N I C", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_nicFocusLost

    private void txt_companyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_companyFocusGained
        txt_company.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "Company", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_companyFocusGained

    private void txt_companyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_companyFocusLost
        txt_company.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "Company", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_companyFocusLost

    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        txt_email.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "E mail", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_emailFocusGained

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        txt_email.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "E mail", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_emailFocusLost

    private void txt_mobileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mobileFocusGained
        txt_mobile.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "Phone No", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_mobileFocusGained

    private void txt_mobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mobileFocusLost
        txt_mobile.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "Phone No", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_mobileFocusLost

    private void txt_faxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_faxFocusGained
        txt_fax.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "Fax No", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_faxFocusGained

    private void txt_faxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_faxFocusLost
        txt_fax.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "Fax No", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_faxFocusLost

    private void txt_streetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_streetFocusGained
        txt_street.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "Street", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_streetFocusGained

    private void txt_streetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_streetFocusLost
        txt_street.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "Street", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_streetFocusLost

    private void txt_cityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cityFocusGained
        txt_city.setBorder(createTitledBorder(new LineBorder(new Color(0, 153, 0), 2), "City", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_cityFocusGained

    private void txt_cityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cityFocusLost
        txt_city.setBorder(createTitledBorder(new LineBorder(new Color(153, 153, 153), 1), "City", TitledBorder.LEADING, TitledBorder.TOP, new Font("Calibri", 1, 15), new Color(102, 102, 102)));
    }//GEN-LAST:event_txt_cityFocusLost

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
        if (Validation.isValidemail(txt_email.getText())) {
            txt_email.setForeground(Color.BLACK);
        } else {
            txt_email.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txt_emailKeyTyped

    private void txt_mobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mobileKeyTyped
        Validation.setDigitsOnly(evt);
        Validation.setLength(evt, txt_mobile.getText(), 12);
    }//GEN-LAST:event_txt_mobileKeyTyped

    private void txt_faxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_faxKeyTyped
        Validation.setDigitsOnly(evt);
        Validation.setLength(evt, txt_fax.getText(), 12);
    }//GEN-LAST:event_txt_faxKeyTyped

    private void txt_cityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cityKeyTyped
        Validation.setLettersOnly(evt);
    }//GEN-LAST:event_txt_cityKeyTyped

    private void txt_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nicKeyTyped
        Validation.setLength(evt, txt_nic.getText(), 12);
    }//GEN-LAST:event_txt_nicKeyTyped

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if (!txt_fname.getText().equals("") | !txt_company.getText().equals("")) {

            int status;
            if (active.isSelected()) {
                status = 1;
            } else {
                status = 0;
            }

            try {
                DB.iud("INSERT INTO supplier VALUES('" + id_supplier.getText() + "','" + txt_fname.getText() + "','" + txt_lname.getText() + "','" + txt_nic.getText() + "','" + txt_company.getText()
                        + "','" + txt_email.getText() + "','" + txt_mobile.getText() + "','" + txt_fax.getText() + "','" + txt_street.getText() + "','" + txt_city.getText() + "','" + status + "' )");
                new Save().setVisible(true);
                clear();
                generateID();
                supplierView.loadTableData();
            } catch (com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException s) {
                if (JOptionPane.showConfirmDialog(this, "Do you want to update this suppliers' data", "Update Supplier Data", JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE) == 0) {
                    
                    try {
                        DB.iud("UPDATE supplier SET fname='" + txt_fname.getText() + "', lname='" + txt_lname.getText() + "', nic='" + txt_nic.getText()
                                + "', company='" + txt_company.getText() + "', email='" + txt_email.getText() + "', mobile='" + txt_mobile.getText() + "', fax='" + txt_fax.getText()
                                + "', street='" + txt_street.getText() + "', city='" + txt_city.getText() + "', state='" + status + "' WHERE id_supplier='" + id_supplier.getText() + "' ");
                        new Save().setVisible(true);
                        clear();
                        generateID();

                        menu.setEnabled(true);
                        supplierView.loadTableData();
                        this.dispose();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Plaese enter Suppliers details here before the save", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        if (JOptionPane.showConfirmDialog(menu, "Do you want clear this data", "Clear", JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE) == 0) {
            clear();
            generateID();
        }
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton active;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton exit;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JPanel header;
    private javax.swing.JLabel id_supplier;
    private javax.swing.JRadioButton inactive;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.ButtonGroup state;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_company;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fax;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_street;
    // End of variables declaration//GEN-END:variables

    private void generateID() {
        try {
            ResultSet rs = DB.search("SELECT COUNT(id_supplier) AS id FROM supplier");
            if (rs.next()) {
                int rowcount = rs.getInt("id");
                rowcount++;
                id_supplier.setText("IS" + String.format("%0" + 6 + "d", rowcount));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clear() {
        txt_fname.setText(null);
        txt_lname.setText(null);
        txt_nic.setText(null);
        txt_company.setText(null);
        txt_email.setText(null);
        txt_mobile.setText(null);
        txt_street.setText(null);
        txt_city.setText(null);
        txt_fax.setText(null);
    }

    public void updateData(String id) {
        try {
            ResultSet rs = DB.search("SELECT * FROM supplier WHERE id_supplier = '" + id + "'");
            if (rs.next()) {
                id_supplier.setText(rs.getString(1));
                txt_fname.setText(rs.getString(2));
                txt_lname.setText(rs.getString(3));
                txt_nic.setText(rs.getString(4));
                txt_company.setText(rs.getString(5));
                txt_email.setText(rs.getString(6));
                txt_mobile.setText(rs.getString(7));
                txt_fax.setText(rs.getString(8));
                txt_street.setText(rs.getString(9));
                txt_city.setText(rs.getString(10));
                if (rs.getInt(11) == 1) {
                    active.setSelected(true);
                } else {
                    inactive.setSelected(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
