/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JPanel;

public class Digital_Printing_Data extends javax.swing.JFrame {

    private int xMouse;
    private int yMouse;
    private Main menu;

    public Digital_Printing_Data() {
        initComponents();
        pressTypeButtopn();
    }

    public Digital_Printing_Data(Main menu) {
        this();
        this.menu = menu;
        this.menu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        basePanel = new javax.swing.JPanel();
        view = new javax.swing.JPanel();
        types = new javax.swing.JButton();
        quality = new javax.swing.JButton();
        prices = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        basePanel.setBackground(new java.awt.Color(38, 57, 75));
        basePanel.setPreferredSize(new java.awt.Dimension(633, 452));
        basePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                basePanelMouseDragged(evt);
            }
        });
        basePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                basePanelMousePressed(evt);
            }
        });
        basePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        basePanel.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 40, 630, 410));

        types.setBackground(new java.awt.Color(38, 57, 75));
        types.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        types.setForeground(new java.awt.Color(204, 204, 204));
        types.setText("Types");
        types.setBorder(null);
        types.setBorderPainted(false);
        types.setContentAreaFilled(false);
        types.setFocusPainted(false);
        types.setOpaque(true);
        types.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                typesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                typesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                typesMouseReleased(evt);
            }
        });
        types.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typesActionPerformed(evt);
            }
        });
        basePanel.add(types, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 160, 38));

        quality.setBackground(new java.awt.Color(38, 57, 75));
        quality.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        quality.setForeground(new java.awt.Color(204, 204, 204));
        quality.setText("Qualities");
        quality.setBorder(null);
        quality.setBorderPainted(false);
        quality.setContentAreaFilled(false);
        quality.setFocusPainted(false);
        quality.setOpaque(true);
        quality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                qualityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                qualityMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                qualityMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                qualityMouseReleased(evt);
            }
        });
        quality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualityActionPerformed(evt);
            }
        });
        basePanel.add(quality, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 1, 160, 38));

        prices.setBackground(new java.awt.Color(38, 57, 75));
        prices.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        prices.setForeground(new java.awt.Color(204, 204, 204));
        prices.setText("Prices");
        prices.setBorder(null);
        prices.setBorderPainted(false);
        prices.setContentAreaFilled(false);
        prices.setFocusPainted(false);
        prices.setOpaque(true);
        prices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pricesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pricesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pricesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pricesMouseReleased(evt);
            }
        });
        prices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricesActionPerformed(evt);
            }
        });
        basePanel.add(prices, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 1, 160, 38));

        btn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit1.png"))); // NOI18N
        btn_Exit.setBorder(null);
        btn_Exit.setBorderPainted(false);
        btn_Exit.setContentAreaFilled(false);
        btn_Exit.setFocusPainted(false);
        btn_Exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit2.png"))); // NOI18N
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        basePanel.add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 1, 25, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void qualityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qualityMouseEntered
        quality.setBackground(new Color(33, 97, 140));
    }//GEN-LAST:event_qualityMouseEntered

    private void qualityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qualityMouseExited
        quality.setBackground(new Color(38, 57, 75));
    }//GEN-LAST:event_qualityMouseExited

    private void qualityMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qualityMousePressed
        quality.setForeground(new Color(0, 204, 204));
        quality.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_qualityMousePressed

    private void qualityMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qualityMouseReleased
        quality.setForeground(new Color(204, 204, 204));
        quality.setBackground(new Color(33, 97, 140));
    }//GEN-LAST:event_qualityMouseReleased

    private void typesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typesMouseEntered
        types.setBackground(new Color(33, 97, 140));
    }//GEN-LAST:event_typesMouseEntered

    private void typesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typesMouseExited
        types.setBackground(new Color(38, 57, 75));
    }//GEN-LAST:event_typesMouseExited

    private void typesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typesMousePressed
        types.setForeground(new Color(0, 204, 204));
        types.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_typesMousePressed

    private void typesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typesMouseReleased
        types.setForeground(new Color(204, 204, 204));
        types.setBackground(new Color(33, 97, 140));
    }//GEN-LAST:event_typesMouseReleased

    private void pricesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricesMouseEntered
        prices.setBackground(new Color(33, 97, 140));
    }//GEN-LAST:event_pricesMouseEntered

    private void pricesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricesMouseExited
        prices.setBackground(new Color(38, 57, 75));
    }//GEN-LAST:event_pricesMouseExited

    private void pricesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricesMousePressed
        prices.setForeground(new Color(0, 204, 204));
        prices.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_pricesMousePressed

    private void pricesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricesMouseReleased
        prices.setForeground(new Color(204, 204, 204));
        prices.setBackground(new Color(33, 97, 140));
    }//GEN-LAST:event_pricesMouseReleased

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void basePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basePanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_basePanelMousePressed

    private void basePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basePanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_basePanelMouseDragged

    private void typesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typesActionPerformed
        pressTypeButtopn();
    }//GEN-LAST:event_typesActionPerformed

    private void qualityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualityActionPerformed
        Digital_Printing_Qualities ty = new Digital_Printing_Qualities();
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) ty.panel);
    }//GEN-LAST:event_qualityActionPerformed

    private void pricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricesActionPerformed
        Digital_Printing_Prices ty = new Digital_Printing_Prices();
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) ty.panel);
    }//GEN-LAST:event_pricesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Digital_Printing_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Digital_Printing_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Digital_Printing_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Digital_Printing_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Digital_Printing_Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton prices;
    private javax.swing.JButton quality;
    private javax.swing.JButton types;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables

    private void pressTypeButtopn() {
        Digital_Printing_Types ty = new Digital_Printing_Types();
        view.removeAll();
        view.revalidate();
        view.repaint();
        view.add((JPanel) ty.panel);
    }
}
