package GUI;

import Database.DB;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.io.File;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class Invoice_DigitalPrinting_View extends javax.swing.JFrame {

    private final DecimalFormat decimalformat = new DecimalFormat("#,##0.00");
    private int xMouse;
    private int yMouse;
    
    public Invoice_DigitalPrinting_View() {
        initComponents();
        tableSettings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        exit = new javax.swing.JButton();
        header = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        invoice_ID = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Customer = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_Print = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txt_subTotal = new javax.swing.JTextField();
        txt_Discount = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_netTotal = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        paidAmount = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        cancelStatus = new javax.swing.JLabel();
        time = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 128, 185)));
        panel.setPreferredSize(new java.awt.Dimension(1150, 660));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        table.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Print Type", "Printing Quality", "Unit Price", "Square Feets", "Quantity", "Discount", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table.setOpaque(false);
        table.setRowHeight(25);
        table.setRowMargin(0);
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(190);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(190);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(100);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(3).setPreferredWidth(150);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(4).setPreferredWidth(100);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(5).setPreferredWidth(150);
            table.getColumnModel().getColumn(6).setResizable(false);
            table.getColumnModel().getColumn(6).setPreferredWidth(197);
        }

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 1080, 340));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit1.png"))); // NOI18N
        exit.setBorder(null);
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setFocusPainted(false);
        exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit2.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1125, 0, 25, 25));

        header.setBackground(new java.awt.Color(250, 251, 250));
        header.setOpaque(true);
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        panel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1148, 25));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 73, 94));
        jLabel2.setText("Invoice");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 30, 120, 40));

        jLabel32.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(66, 73, 73));
        jLabel32.setText("Invoice No");
        panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 90, 80, 25));

        invoice_ID.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        panel.add(invoice_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 220, 25));

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(66, 73, 73));
        jLabel24.setText("Customer");
        panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 130, 80, 25));

        Customer.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panel.add(Customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 460, 25));

        date.setEditable(false);
        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        panel.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 160, 25));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(66, 73, 73));
        jLabel13.setText("Date");
        panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 40, 25));

        btn_Print.setBackground(new java.awt.Color(41, 128, 185));
        btn_Print.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Print.setForeground(new java.awt.Color(255, 255, 255));
        btn_Print.setText("Print");
        btn_Print.setBorder(null);
        btn_Print.setBorderPainted(false);
        btn_Print.setContentAreaFilled(false);
        btn_Print.setFocusPainted(false);
        btn_Print.setOpaque(true);
        btn_Print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_PrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_PrintMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_PrintMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_PrintMouseReleased(evt);
            }
        });
        btn_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrintActionPerformed(evt);
            }
        });
        panel.add(btn_Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 120, 30));

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(66, 73, 73));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Sub Total");
        panel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 515, 60, 30));

        txt_subTotal.setEditable(false);
        txt_subTotal.setBackground(new java.awt.Color(255, 255, 255));
        txt_subTotal.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txt_subTotal.setForeground(new java.awt.Color(39, 55, 70));
        txt_subTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_subTotal.setText("0.00");
        txt_subTotal.setEnabled(false);
        panel.add(txt_subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 515, 180, 30));

        txt_Discount.setEditable(false);
        txt_Discount.setBackground(new java.awt.Color(255, 255, 255));
        txt_Discount.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txt_Discount.setForeground(new java.awt.Color(39, 55, 70));
        txt_Discount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Discount.setText("0");
        txt_Discount.setEnabled(false);
        panel.add(txt_Discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 180, 30));

        jLabel34.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(66, 73, 73));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("Discount  (%)");
        panel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 100, 30));

        jLabel36.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(66, 73, 73));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Net Total");
        panel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 585, 60, 30));

        txt_netTotal.setEditable(false);
        txt_netTotal.setBackground(new java.awt.Color(255, 255, 255));
        txt_netTotal.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txt_netTotal.setForeground(new java.awt.Color(39, 55, 70));
        txt_netTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_netTotal.setText("0.00");
        txt_netTotal.setEnabled(false);
        panel.add(txt_netTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 585, 180, 30));

        jLabel38.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 153, 51));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Balance");
        panel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 60, 40));

        balance.setEditable(false);
        balance.setBackground(new java.awt.Color(255, 255, 255));
        balance.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        balance.setForeground(new java.awt.Color(39, 55, 70));
        balance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        balance.setText("0.00");
        balance.setEnabled(false);
        panel.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, 180, 40));

        paidAmount.setEditable(false);
        paidAmount.setBackground(new java.awt.Color(255, 255, 255));
        paidAmount.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        paidAmount.setForeground(new java.awt.Color(39, 55, 70));
        paidAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paidAmount.setText("0.00");
        paidAmount.setEnabled(false);
        panel.add(paidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 515, 180, 30));

        jLabel37.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(66, 73, 73));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Paid");
        panel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 515, 60, 30));

        cancelStatus.setFont(new java.awt.Font("Chloreal", 1, 40)); // NOI18N
        cancelStatus.setForeground(new java.awt.Color(255, 0, 0));
        panel.add(cancelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 250, 40));

        time.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        panel.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 90, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void btn_PrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrintMouseEntered
        btn_Print.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_PrintMouseEntered

    private void btn_PrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrintMouseExited
        btn_Print.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_btn_PrintMouseExited

    private void btn_PrintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrintMousePressed
        btn_Print.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_btn_PrintMousePressed

    private void btn_PrintMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrintMouseReleased
        btn_Print.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_PrintMouseReleased

    private void btn_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            String path = "jasperReports\\Invoice_Printing.jrxml";

            String s = new File(path).getAbsolutePath().replace("\\", "\\\\");
            String subReportpath = (s.split("Invoice_Printing.jrxml"))[0];

            Map<String, Object> m = new HashMap();
            m.put("subPath", subReportpath); // send subReport path
            m.put("invoice_no", invoice_ID.getText());
            m.put("isPrintCopy", "Print Copy");

            JasperReport cp = JasperCompileManager.compileReport(path);
            JasperPrint fr = JasperFillManager.fillReport(cp, m, DB.getConnection());
            JasperViewer.viewReport(fr, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        this.setCursor(null);
    }//GEN-LAST:event_btn_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice_DigitalPrinting_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice_DigitalPrinting_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice_DigitalPrinting_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice_DigitalPrinting_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice_DigitalPrinting_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Customer;
    private javax.swing.JTextField balance;
    private javax.swing.JButton btn_Print;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cancelStatus;
    private javax.swing.JTextField date;
    private javax.swing.JButton exit;
    private javax.swing.JLabel header;
    private javax.swing.JLabel invoice_ID;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField paidAmount;
    public javax.swing.JPanel panel;
    private javax.swing.JTable table;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txt_Discount;
    private javax.swing.JTextField txt_netTotal;
    private javax.swing.JTextField txt_subTotal;
    // End of variables declaration//GEN-END:variables

    private void tableSettings() {
        JTableHeader tableHeader = table.getTableHeader();
        tableHeader.setFont(new Font("Calibri", Font.BOLD, 14));
        ((DefaultTableCellRenderer) tableHeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);

        DefaultTableCellRenderer right = new DefaultTableCellRenderer();
        right.setHorizontalAlignment(JLabel.RIGHT);

        table.getColumnModel().getColumn(2).setCellRenderer(center);
        table.getColumnModel().getColumn(3).setCellRenderer(center);
        table.getColumnModel().getColumn(5).setCellRenderer(center);
        table.getColumnModel().getColumn(5).setCellRenderer(right);
        table.getColumnModel().getColumn(6).setCellRenderer(right);
    }

     public void viewInvoiceData(String invoiceNo) {
        SimpleDateFormat time24format = new SimpleDateFormat("HH:mm:ss");
        SimpleDateFormat time12format = new SimpleDateFormat("hh:mm:ss aa");
        try {
            ResultSet rs = DB.search(" SELECT invoice.id_invoice, invoice.`date`, invoice.id_customer, customer.fname, customer.lname,"
                    + " invoice.subtotal, invoice.discount, invoice.net_total, invoice.paid_amount, invoice.balance, invoice.`time`, invoice.payment_type,"
                    + " invoice.state FROM customer INNER JOIN invoice ON customer.id_customer=invoice.id_customer WHERE invoice.id_invoice = '" + invoiceNo + "' ");
            if (rs.next()) {
                invoice_ID.setText(rs.getString(1));
                date.setText(rs.getString(2));
                Customer.setText(rs.getString(3) + " -  " + rs.getString(4) + " " + rs.getString(5));
                txt_subTotal.setText(decimalformat.format(rs.getDouble(6)));
                txt_Discount.setText(rs.getString(7));
                txt_netTotal.setText(decimalformat.format(rs.getDouble(8)));
                paidAmount.setText(decimalformat.format(rs.getDouble(9)));
                balance.setText(decimalformat.format(rs.getDouble(10)));
                time.setText(time12format.format(time24format.parse(rs.getString(11))));
                if (rs.getInt(13) == 0) {
                    cancelStatus.setText("canceled");
                } else {
                    cancelStatus.setText(null);
                }
            }

            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            ResultSet rs2 = DB.search(" SELECT print_type.`type`, print_quality.quality, invoice_item_printing.unit_price, invoice_item_printing.squre_feets, invoice_item_printing.qty, "
                    + "invoice_item_printing.discount, invoice_item_printing.amount FROM invoice_item_printing INNER JOIN print_price ON invoice_item_printing.`print_price`=print_price.id "
                    + "INNER JOIN print_type ON print_price.type_id=print_type.id INNER JOIN print_quality ON print_price.quality_id=print_quality.id WHERE invoice_item_printing.id_invoice = '" + invoiceNo + "' ");
            while (rs2.next()) {
                Vector v = new Vector();
                v.add(rs2.getString(1));
                v.add(rs2.getString(2));
                v.add(rs2.getString(3));
                v.add(rs2.getString(4));
                v.add(rs2.getString(5));
                v.add(decimalformat.format(rs2.getDouble(6)));
                v.add(decimalformat.format(rs2.getDouble(7)));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
