package GUI;

import Database.DB;
import Model.Validation;
import java.awt.Color;
import java.sql.ResultSet;
import java.text.DecimalFormat;

public class Item_Discount extends javax.swing.JFrame {

    private Main menu;
    private Invoice invoice;
    private Invoice_Digital_Printing inv_DigiPrint;

    private double qty;
    private double total;
    private String unit;
    private double item_price;
    private String stock_id;
    private final DecimalFormat deci = new DecimalFormat("###0.00");
    private boolean digiPrint;
    private double digi_amount;
    private int rowNo;
    String fulldiscount;

    public Item_Discount() {
        initComponents();
    }

    public Item_Discount(Main menu, Invoice inv, String stockID, double qty, String unit, int rowid,double price) {
        this();
        this.menu = menu;
        this.menu.setEnabled(false);
        this.invoice = inv;
        this.qty = qty;
        this.stock_id = stockID;
        this.unit = unit;
        this.item_price=price;
        this.rowNo = rowid;
        getItemData(stockID);
    }

    public Item_Discount(Main menu, Invoice inv, double total) {
        this();
        this.menu = menu;
        this.menu.setEnabled(false);
        this.invoice = inv;
        this.total = total;
        fulldiscount = "ok";
    }

    public Item_Discount(Invoice_Digital_Printing aThis, Main menu, String amount, int row) {
        this();
        this.menu = menu;
        this.inv_DigiPrint = aThis;
        this.digiPrint = true;
        this.digi_amount = Double.parseDouble(amount.replace(",", ""));
        this.rowNo = row;
        this.menu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        productName = new javax.swing.JLabel();
        btn_Cancel = new javax.swing.JButton();
        btn_Done = new javax.swing.JButton();
        txt_Discount = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        amount = new javax.swing.JRadioButton();
        percen = new javax.swing.JRadioButton();
        txt_Rate = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        productName1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productName.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        productName.setForeground(new java.awt.Color(41, 128, 185));
        jPanel1.add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 440, 30));

        btn_Cancel.setBackground(new java.awt.Color(179, 182, 183));
        btn_Cancel.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btn_Cancel.setText("Cancel");
        btn_Cancel.setBorder(null);
        btn_Cancel.setBorderPainted(false);
        btn_Cancel.setContentAreaFilled(false);
        btn_Cancel.setFocusPainted(false);
        btn_Cancel.setOpaque(true);
        btn_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_CancelMouseReleased(evt);
            }
        });
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 90, 30));

        btn_Done.setBackground(new java.awt.Color(41, 128, 185));
        btn_Done.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        btn_Done.setForeground(new java.awt.Color(255, 255, 255));
        btn_Done.setText("Done");
        btn_Done.setBorder(null);
        btn_Done.setBorderPainted(false);
        btn_Done.setContentAreaFilled(false);
        btn_Done.setFocusPainted(false);
        btn_Done.setOpaque(true);
        btn_Done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DoneMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_DoneMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_DoneMouseReleased(evt);
            }
        });
        btn_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoneActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Done, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 90, 30));

        txt_Discount.setEditable(false);
        txt_Discount.setBackground(new java.awt.Color(255, 255, 255));
        txt_Discount.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txt_Discount.setForeground(new java.awt.Color(39, 55, 70));
        txt_Discount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Discount.setFocusable(false);
        jPanel1.add(txt_Discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 200, 30));

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(66, 73, 73));
        jLabel34.setText("Discount");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 60, 20));

        buttonGroup1.add(amount);
        amount.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        amount.setText("Amount");
        amount.setContentAreaFilled(false);
        amount.setFocusPainted(false);
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        buttonGroup1.add(percen);
        percen.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        percen.setText("Percentage");
        percen.setContentAreaFilled(false);
        percen.setFocusPainted(false);
        jPanel1.add(percen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_Rate.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txt_Rate.setForeground(new java.awt.Color(39, 55, 70));
        txt_Rate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Rate.setText("0");
        txt_Rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RateActionPerformed(evt);
            }
        });
        txt_Rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_RateKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RateKeyTyped(evt);
            }
        });
        jPanel1.add(txt_Rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, 30));

        jLabel35.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(66, 73, 73));
        jLabel35.setText("Rate");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, 20));

        productName1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        productName1.setForeground(new java.awt.Color(41, 128, 185));
        productName1.setText("Discounts");
        jPanel1.add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseEntered
        btn_Cancel.setBackground(new Color(144, 148, 151));
    }//GEN-LAST:event_btn_CancelMouseEntered

    private void btn_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseExited
        btn_Cancel.setBackground(new Color(179, 182, 183));
    }//GEN-LAST:event_btn_CancelMouseExited

    private void btn_CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMousePressed
        btn_Cancel.setBackground(new Color(98, 101, 103));
    }//GEN-LAST:event_btn_CancelMousePressed

    private void btn_CancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseReleased
        btn_Cancel.setBackground(new Color(144, 148, 151));
    }//GEN-LAST:event_btn_CancelMouseReleased

    private void btn_DoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoneMouseEntered
        btn_Done.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_DoneMouseEntered

    private void btn_DoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoneMouseExited
        btn_Done.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_btn_DoneMouseExited

    private void btn_DoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoneMousePressed
        btn_Done.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_btn_DoneMousePressed

    private void btn_DoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoneMouseReleased
        btn_Done.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_DoneMouseReleased

    private void btn_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoneActionPerformed
        if (!txt_Discount.getText().isEmpty()) {
            if (digiPrint) {
                DecimalFormat decim = new DecimalFormat("#,##0.00");
                inv_DigiPrint.discounts(txt_Discount.getText(), decim.format(digi_amount - Double.parseDouble(txt_Discount.getText())), rowNo);
            } else if (fulldiscount != null) {
                double dis = Double.parseDouble(txt_Discount.getText());
                invoice.txt_fulldiscount.setText(deci.format(dis));
                invoice.getNetTotal();
            } else {
                for (int i = 0; i < invoice.table.getRowCount(); i++) {
                    if (Integer.parseInt(invoice.table.getValueAt(i, 0).toString())==rowNo && invoice.table.getValueAt(i, 4).toString().equals(unit)) {
                        double dis = Double.parseDouble(txt_Discount.getText());
                        invoice.table.setValueAt(deci.format(dis* qty), i, 7);
                        invoice.table.setValueAt(deci.format((item_price) - (dis* qty)), i, 8);
//                        invoice.getSubTotal();
                        invoice.getDiscount();
                        invoice.getNetTotal();

                    }
                }
            }
            menu.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_DoneActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void txt_RateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RateKeyTyped
        if (percen.isSelected() || amount.isSelected()) {
            if (Character.isLetter(evt.getKeyChar())) {
                evt.consume();
            }
            if (percen.isSelected()) {
                Validation.setLength(evt, txt_Rate.getText(), 6);
            } else {
                Validation.setLength(evt, txt_Rate.getText(), 10);
            }
        } else {
            evt.consume();
        }

    }//GEN-LAST:event_txt_RateKeyTyped

    private void txt_RateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RateKeyReleased
        if (percen.isSelected()) {
            if (!txt_Rate.getText().isEmpty()) {
                if (Double.parseDouble(txt_Rate.getText()) < 101) {
                    if (digiPrint) {
                        txt_Discount.setText(String.valueOf((digi_amount * Double.parseDouble(txt_Rate.getText())) / 100));
                    } else if (fulldiscount != null) {
                        txt_Discount.setText(String.valueOf((total * Double.parseDouble(txt_Rate.getText())) / 100));
                    } else {
                        txt_Discount.setText(String.valueOf((qty * item_price * Double.parseDouble(txt_Rate.getText())) / 100));
                    }
                }
            }
        } else {
            if (digiPrint) {
                txt_Discount.setText(txt_Rate.getText());
            } else if (fulldiscount != null) {
                txt_Discount.setText(txt_Rate.getText());
            } else {
                txt_Discount.setText(txt_Rate.getText());
            }
        }
    }//GEN-LAST:event_txt_RateKeyReleased

    private void txt_RateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RateActionPerformed
        btn_Done.grabFocus();
    }//GEN-LAST:event_txt_RateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Item_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Item_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Item_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Item_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Item_Discount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton amount;
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Done;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton percen;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productName1;
    private javax.swing.JTextField txt_Discount;
    private javax.swing.JTextField txt_Rate;
    // End of variables declaration//GEN-END:variables

    private void getItemData(String stockID) {
        try {
            if (stockID.equals("*****")) {
                productName.setText("Uncount Item");
            } else {
                ResultSet rs = DB.search("SELECT product.productname, product_stock.retail_price FROM product_stock "
                        + "INNER JOIN product ON product_stock.id_product=product.id_product WHERE product_stock.idproduct_stock='" + stockID + "'");
                if (rs.next()) {
                    productName.setText(rs.getString("productname"));
//                    item_price = rs.getDouble("retail_price");
                }
//                if (unit.equals("Bottle")) {
//                    item_price = item_price * 0.75;
//                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
