package GUI;

import Database.DB;
import com.inet.report.EngineRenderData;
import com.inet.viewer.SwingReportViewer;
import com.inet.viewer.URLRenderData;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Cursor;
import java.io.File;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class Reports extends javax.swing.JFrame {

    public String supplierName;
    public String suppID;
    private Main menu;
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    public Reports() {
        initComponents();
        hideComponents();
        JTextFieldDateEditor f = (JTextFieldDateEditor) sales_DateFrom.getDateEditor();
        f.setEditable(false);
        f.setBackground(Color.WHITE);
        f = (JTextFieldDateEditor) sales_DateTo.getDateEditor();
        f.setEditable(false);
        f.setBackground(Color.WHITE);
        f = (JTextFieldDateEditor) srn_DateFrom.getDateEditor();
        f.setEditable(false);
        f.setBackground(Color.WHITE);
        f = (JTextFieldDateEditor) srn_DateTo.getDateEditor();
        f.setEditable(false);
        f.setBackground(Color.WHITE);
    }

    public Reports(Main m) {
        this();
        this.menu = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sales_period = new javax.swing.JComboBox<>();
        to1 = new javax.swing.JLabel();
        from1 = new javax.swing.JLabel();
        sales_DateTo = new com.toedter.calendar.JDateChooser();
        sales_DateFrom = new com.toedter.calendar.JDateChooser();
        btn_getSalesReport = new javax.swing.JButton();
        reports1 = new javax.swing.JLabel();
        srn_period = new javax.swing.JComboBox<>();
        to2 = new javax.swing.JLabel();
        from2 = new javax.swing.JLabel();
        srn_DateTo = new com.toedter.calendar.JDateChooser();
        srn_DateFrom = new com.toedter.calendar.JDateChooser();
        btn_getSRNreport = new javax.swing.JButton();
        reports2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        reportType = new javax.swing.JComboBox<>();
        btn_OtherReports = new javax.swing.JButton();
        supplierID = new javax.swing.JTextField();
        btn_SearchSupplier = new javax.swing.JButton();
        sup = new javax.swing.JLabel();
        reports3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setPreferredSize(new java.awt.Dimension(1080, 660));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 73, 94));
        jLabel2.setText("Reports");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 50));

        sales_period.setEditable(true);
        sales_period.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        sales_period.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Last 7 Days", "Last 30 Days", "Custom" }));
        sales_period.setBorder(null);
        sales_period.setFocusable(false);
        sales_period.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_periodActionPerformed(evt);
            }
        });
        panel.add(sales_period, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 260, 30));

        to1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        to1.setText("To");
        panel.add(to1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 30, 25));

        from1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        from1.setText("From");
        panel.add(from1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 40, 25));

        sales_DateTo.setDateFormatString("yyyy-MM-dd");
        sales_DateTo.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        panel.add(sales_DateTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 180, 25));

        sales_DateFrom.setDateFormatString("yyyy-MM-dd");
        sales_DateFrom.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        panel.add(sales_DateFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 180, 25));

        btn_getSalesReport.setBackground(new java.awt.Color(41, 128, 185));
        btn_getSalesReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_getSalesReport.setForeground(new java.awt.Color(255, 255, 255));
        btn_getSalesReport.setText("Open");
        btn_getSalesReport.setBorder(null);
        btn_getSalesReport.setBorderPainted(false);
        btn_getSalesReport.setContentAreaFilled(false);
        btn_getSalesReport.setFocusPainted(false);
        btn_getSalesReport.setOpaque(true);
        btn_getSalesReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_getSalesReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_getSalesReportMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_getSalesReportMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_getSalesReportMouseReleased(evt);
            }
        });
        btn_getSalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getSalesReportActionPerformed(evt);
            }
        });
        panel.add(btn_getSalesReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, 80, 30));

        reports1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        reports1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Sales Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        panel.add(reports1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1130, 140));

        srn_period.setEditable(true);
        srn_period.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        srn_period.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Last 7 Days", "Last 30 Days", "Custom" }));
        srn_period.setBorder(null);
        srn_period.setFocusable(false);
        srn_period.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srn_periodActionPerformed(evt);
            }
        });
        panel.add(srn_period, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 260, 30));

        to2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        to2.setText("To");
        panel.add(to2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 30, 25));

        from2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        from2.setText("From");
        panel.add(from2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 40, 25));

        srn_DateTo.setDateFormatString("yyyy-MM-dd");
        srn_DateTo.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        panel.add(srn_DateTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 180, 25));

        srn_DateFrom.setDateFormatString("yyyy-MM-dd");
        srn_DateFrom.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        panel.add(srn_DateFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 180, 25));

        btn_getSRNreport.setBackground(new java.awt.Color(41, 128, 185));
        btn_getSRNreport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_getSRNreport.setForeground(new java.awt.Color(255, 255, 255));
        btn_getSRNreport.setText("Open");
        btn_getSRNreport.setBorder(null);
        btn_getSRNreport.setBorderPainted(false);
        btn_getSRNreport.setContentAreaFilled(false);
        btn_getSRNreport.setFocusPainted(false);
        btn_getSRNreport.setOpaque(true);
        btn_getSRNreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_getSRNreportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_getSRNreportMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_getSRNreportMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_getSRNreportMouseReleased(evt);
            }
        });
        btn_getSRNreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getSRNreportActionPerformed(evt);
            }
        });
        panel.add(btn_getSRNreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 330, 80, 30));

        reports2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        reports2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Sales Return Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        panel.add(reports2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 1130, 140));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel10.setText("Report");
        panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 50, 30));

        reportType.setEditable(true);
        reportType.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        reportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select -", "Stock Report", "Product Item Report", "Supplier History" }));
        reportType.setBorder(null);
        reportType.setFocusable(false);
        reportType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportTypeActionPerformed(evt);
            }
        });
        panel.add(reportType, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 260, 30));

        btn_OtherReports.setBackground(new java.awt.Color(41, 128, 185));
        btn_OtherReports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_OtherReports.setForeground(new java.awt.Color(255, 255, 255));
        btn_OtherReports.setText("Open");
        btn_OtherReports.setBorder(null);
        btn_OtherReports.setBorderPainted(false);
        btn_OtherReports.setContentAreaFilled(false);
        btn_OtherReports.setFocusPainted(false);
        btn_OtherReports.setOpaque(true);
        btn_OtherReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_OtherReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_OtherReportsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_OtherReportsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_OtherReportsMouseReleased(evt);
            }
        });
        btn_OtherReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OtherReportsActionPerformed(evt);
            }
        });
        panel.add(btn_OtherReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 540, 80, 30));

        supplierID.setEditable(false);
        supplierID.setBackground(new java.awt.Color(255, 255, 255));
        supplierID.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        panel.add(supplierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 170, 30));

        btn_SearchSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/find.png"))); // NOI18N
        btn_SearchSupplier.setBorderPainted(false);
        btn_SearchSupplier.setFocusPainted(false);
        btn_SearchSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchSupplierActionPerformed(evt);
            }
        });
        panel.add(btn_SearchSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 30, 30));

        sup.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        sup.setText("Supplier");
        panel.add(sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 60, 30));

        reports3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        reports3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Other Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        panel.add(reports3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 1130, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_getSalesReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_getSalesReportMouseEntered
        btn_getSalesReport.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_getSalesReportMouseEntered

    private void btn_getSalesReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_getSalesReportMouseExited
        btn_getSalesReport.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_btn_getSalesReportMouseExited

    private void btn_getSalesReportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_getSalesReportMousePressed
        btn_getSalesReport.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_btn_getSalesReportMousePressed

    private void btn_getSalesReportMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_getSalesReportMouseReleased
        btn_getSalesReport.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_getSalesReportMouseReleased

    private void btn_getSRNreportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_getSRNreportMouseEntered
        btn_getSRNreport.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_getSRNreportMouseEntered

    private void btn_getSRNreportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_getSRNreportMouseExited
        btn_getSRNreport.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_btn_getSRNreportMouseExited

    private void btn_getSRNreportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_getSRNreportMousePressed
        btn_getSRNreport.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_btn_getSRNreportMousePressed

    private void btn_getSRNreportMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_getSRNreportMouseReleased
        btn_getSRNreport.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_getSRNreportMouseReleased

    private void btn_OtherReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_OtherReportsMouseEntered
        btn_OtherReports.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_OtherReportsMouseEntered

    private void btn_OtherReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_OtherReportsMouseExited
        btn_OtherReports.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_btn_OtherReportsMouseExited

    private void btn_OtherReportsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_OtherReportsMousePressed
        btn_OtherReports.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_btn_OtherReportsMousePressed

    private void btn_OtherReportsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_OtherReportsMouseReleased
        btn_OtherReports.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_OtherReportsMouseReleased

    private void btn_getSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getSalesReportActionPerformed
        menu.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        switch (sales_period.getSelectedIndex()) {
            case 0: //Today
                printSalesReport(LocalDate.now().toString(), LocalDate.now().toString());
                break;
            case 1: // Last 7 Days
                printSalesReport(LocalDate.now().minusDays(6).toString(), LocalDate.now().toString());
                sales_period.setSelectedIndex(0);
                break;
            case 2: // Last 30 Days
                printSalesReport(LocalDate.now().minusDays(29).toString(), LocalDate.now().toString());
                sales_period.setSelectedIndex(0);
                break;
            case 3: // Custom
                if (sales_DateFrom.getDate() == null | sales_DateTo.getDate() == null) {
                    JOptionPane.showMessageDialog(menu, "Please select the date range to get report", "Select Date Range", JOptionPane.WARNING_MESSAGE);
                } else {
                    printSalesReport(dateFormat.format(sales_DateFrom.getDate()), dateFormat.format(sales_DateTo.getDate()));

                    sales_period.setSelectedIndex(0);
                    sales_DateFrom.setDate(null);
                    sales_DateFrom.setVisible(false);
                    sales_DateTo.setDate(null);
                    sales_DateTo.setVisible(false);
                    from1.setVisible(false);
                    to1.setVisible(false);
                    break;
                }
        } // end of switch statement
        menu.setCursor(null);
    }//GEN-LAST:event_btn_getSalesReportActionPerformed

    private void sales_periodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_periodActionPerformed
        if (sales_period.getSelectedItem().toString().equals("Custom")) {
            from1.setVisible(true);
            sales_DateFrom.setVisible(true);
            to1.setVisible(true);
            sales_DateTo.setVisible(true);
        } else {
            from1.setVisible(false);
            sales_DateFrom.setVisible(false);
            to1.setVisible(false);
            sales_DateTo.setVisible(false);
        }
    }//GEN-LAST:event_sales_periodActionPerformed

    private void srn_periodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srn_periodActionPerformed
        if (srn_period.getSelectedItem().toString().equals("Custom")) {
            from2.setVisible(true);
            srn_DateFrom.setVisible(true);
            to2.setVisible(true);
            srn_DateTo.setVisible(true);
        } else {
            from2.setVisible(false);
            srn_DateFrom.setVisible(false);
            to2.setVisible(false);
            srn_DateTo.setVisible(false);
        }
    }//GEN-LAST:event_srn_periodActionPerformed

    private void btn_getSRNreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getSRNreportActionPerformed
        menu.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        switch (srn_period.getSelectedIndex()) {
            case 0: //Today
                printSalesReturnReport(LocalDate.now().toString(), LocalDate.now().toString());
                break;
            case 1: // Last 7 Days
                printSalesReturnReport(LocalDate.now().minusDays(6).toString(), LocalDate.now().toString());
                srn_period.setSelectedIndex(0);
                break;
            case 2: // Last 30 Days
                printSalesReturnReport(LocalDate.now().minusDays(29).toString(), LocalDate.now().toString());
                srn_period.setSelectedIndex(0);
                break;
            case 3: // Custom
                if (srn_DateFrom.getDate() == null | srn_DateTo.getDate() == null) {
                    JOptionPane.showMessageDialog(this, "Please select the date range to get report", "Select Date Range", JOptionPane.WARNING_MESSAGE);
                } else {
                    printSalesReturnReport(dateFormat.format(srn_DateFrom.getDate()), dateFormat.format(srn_DateTo.getDate()));

                    srn_period.setSelectedIndex(0);
                    from2.setVisible(false);
                    srn_DateFrom.setDate(null);
                    srn_DateFrom.setVisible(false);
                    to2.setVisible(false);
                    srn_DateTo.setDate(null);
                    srn_DateTo.setVisible(false);
                    break;
                }
        }
        menu.setCursor(null);
    }//GEN-LAST:event_btn_getSRNreportActionPerformed

    private void reportTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportTypeActionPerformed
        if (reportType.getSelectedIndex() == 3) {
            supplierID.setVisible(true);
            btn_SearchSupplier.setVisible(true);
            sup.setVisible(true);
        } else {
            supplierID.setVisible(false);
            btn_SearchSupplier.setVisible(false);
            sup.setVisible(false);
        }
    }//GEN-LAST:event_reportTypeActionPerformed

    private void btn_OtherReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OtherReportsActionPerformed
        menu.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        switch (reportType.getSelectedIndex()) {
            case 1: // Stock Report
                printStockReprot();
                reportType.setSelectedIndex(0);
                break;
            case 2: // Product Item Report
                printProductReprot();
                reportType.setSelectedIndex(0);
                break;
            case 3: // Supplier History Report
                if (supplierID.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(menu, "Select a supplier to generate report", "Select Supplier", JOptionPane.WARNING_MESSAGE);
                } else {
                    printSupplierHistoryReprot();
                    reportType.setSelectedIndex(0);
                    supplierID.setText(null);
                    supplierID.setVisible(false);
                    sup.setVisible(false);
                    btn_SearchSupplier.setVisible(false);
                }
                break;
        }
        menu.setCursor(null);

    }//GEN-LAST:event_btn_OtherReportsActionPerformed

    private void btn_SearchSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchSupplierActionPerformed
        SearchSupplier sup = new SearchSupplier(menu, this);
        sup.setVisible(true);
    }//GEN-LAST:event_btn_SearchSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_OtherReports;
    private javax.swing.JButton btn_SearchSupplier;
    private javax.swing.JButton btn_getSRNreport;
    private javax.swing.JButton btn_getSalesReport;
    private javax.swing.JLabel from1;
    private javax.swing.JLabel from2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> reportType;
    private javax.swing.JLabel reports1;
    private javax.swing.JLabel reports2;
    private javax.swing.JLabel reports3;
    private com.toedter.calendar.JDateChooser sales_DateFrom;
    private com.toedter.calendar.JDateChooser sales_DateTo;
    private javax.swing.JComboBox<String> sales_period;
    private com.toedter.calendar.JDateChooser srn_DateFrom;
    private com.toedter.calendar.JDateChooser srn_DateTo;
    private javax.swing.JComboBox<String> srn_period;
    private javax.swing.JLabel sup;
    public javax.swing.JTextField supplierID;
    private javax.swing.JLabel to1;
    private javax.swing.JLabel to2;
    // End of variables declaration//GEN-END:variables

    private void hideComponents() {
        sales_DateFrom.setVisible(false);
        sales_DateTo.setVisible(false);
        from1.setVisible(false);
        to1.setVisible(false);

        from2.setVisible(false);
        srn_DateFrom.setVisible(false);
        to2.setVisible(false);
        srn_DateTo.setVisible(false);

        supplierID.setVisible(false);
        btn_SearchSupplier.setVisible(false);
        sup.setVisible(false);
    }

    private void printSalesReport(String dateFrom, String dateTo) {
        try {
            JFrame frame = new JFrame("i-net Clear Reports Report Viewer");
            SwingReportViewer viewer;
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            String path = "jasperReports\\SalesReport.jasper";

            String s = new File(path).getAbsolutePath().replace("\\", "\\\\");
            String subReportpath = (s.split("SalesReport.jasper"))[0];

            Map<String, Object> m = new HashMap();
            m.put("subPath", subReportpath); // send subReport path
            m.put("dateFrom", dateFrom);
            m.put("dateTo", dateTo);

//            JasperReport cp = JasperCompileManager.compileReport(path);
            JasperPrint fr = JasperFillManager.fillReport(path, m, DB.getConnection());
            JasperViewer.viewReport(fr, false);
            
//            /////////////////////////
//            EngineRenderData myConnection = new EngineRenderData("");
////            URLRenderData myConnection = new URLRenderData("http://127.0.0.1:8087/?report=file:Report1.rpt" );
//            viewer = new SwingReportViewer();
//            viewer.addNewReportView(myConnection);
//            frame.getContentPane().add(viewer);
//
//            // Display the window.
//            frame.pack();
//            frame.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void printSalesReturnReport(String dateFrom, String dateTo) {

        try {
            String path = "jasperReports\\SalesReturnReport.jrxml";

            String s = new File(path).getAbsolutePath().replace("\\", "\\\\");
            String subReportpath = (s.split("SalesReturnReport.jrxml"))[0];

            Map<String, Object> m = new HashMap();
            m.put("subPath", subReportpath); // send subReport path
            m.put("dateFrom", dateFrom);
            m.put("dateTo", dateTo);

            JasperReport cp = JasperCompileManager.compileReport(path);
            JasperPrint fr = JasperFillManager.fillReport(cp, m, DB.getConnection());
            JasperViewer.viewReport(fr, false);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void printStockReprot() {
        menu.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            String path = "jasperReports\\Stock.jrxml";
            Map<String, Object> m = new HashMap();

            JasperReport cp = JasperCompileManager.compileReport(path);
            JasperPrint fr = JasperFillManager.fillReport(cp, m, DB.getConnection());
            JasperViewer.viewReport(fr, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
        menu.setCursor(null);
    }

    private void printProductReprot() {
        try {
            String path = "jasperReports\\Products.jrxml";
            Map<String, Object> m = new HashMap();

            JasperReport cp = JasperCompileManager.compileReport(path);
            JasperPrint fr = JasperFillManager.fillReport(cp, m, DB.getConnection());
            JasperViewer.viewReport(fr, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void printSupplierHistoryReprot() {
        if (suppID == null | supplierName == null) {

        } else {
            try {
                String path = "jasperReports\\SupplierHistory.jrxml";

                String s = new File(path).getAbsolutePath().replace("\\", "\\\\");
                String subReportpath = (s.split("SupplierHistory.jrxml"))[0];

                Map<String, Object> m = new HashMap();
                m.put("subPath", subReportpath); // send subReport path
                m.put("id_supplier", suppID);
                m.put("supplier", supplierName);

                JasperReport cp = JasperCompileManager.compileReport(path);
                JasperPrint fr = JasperFillManager.fillReport(cp, m, DB.getConnection());
                JasperViewer.viewReport(fr, false);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
