package GUI;

import Database.DB;
import Model.Save;
import Model.Validation;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class Supplier_Payments extends javax.swing.JFrame {

    private Main menu;
    private String user_Type;
    private DecimalFormat decimalformat = new DecimalFormat("00.00");
    private final SimpleDateFormat dateFomrmat = new SimpleDateFormat("yyyy-MM-dd");

    public Supplier_Payments() {
        initComponents();
        payMethod.setVisible(false);
        generateID();
        tableSettings();
        voucherDate.setDate(new Date());
        JTextFieldDateEditor f = (JTextFieldDateEditor) voucherDate.getDateEditor();
        f.setEditable(false);
        f.setBackground(Color.WHITE);
        f = (JTextFieldDateEditor) txt_ChqDate.getDateEditor();
        f.setEditable(false);
        f.setBackground(Color.WHITE);
    }

    public Supplier_Payments(Main me, String user) {
        this();
        this.menu = me;
        this.user_Type = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        voucherNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        supplierID = new javax.swing.JTextField();
        voucherDate = new com.toedter.calendar.JDateChooser();
        btn_Cash = new javax.swing.JRadioButton();
        btn_Cheque = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btn_Previous = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        payMethod = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        label33 = new javax.swing.JLabel();
        txt_ChqNo = new javax.swing.JTextField();
        txt_ChqDate = new com.toedter.calendar.JDateChooser();
        label44 = new javax.swing.JLabel();
        txt_bankName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        supplierName = new javax.swing.JLabel();
        voucherValue = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setMaximumSize(new java.awt.Dimension(1080, 660));
        panel.setMinimumSize(new java.awt.Dimension(1080, 660));
        panel.setPreferredSize(new java.awt.Dimension(1080, 660));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voucherNo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        voucherNo.setForeground(new java.awt.Color(66, 73, 73));
        panel.add(voucherNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 230, 25));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 73, 73));
        jLabel3.setText("Supplier");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 70, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 73, 73));
        jLabel4.setText("Date");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, -1, 25));

        supplierID.setEditable(false);
        supplierID.setBackground(new java.awt.Color(255, 255, 255));
        supplierID.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        panel.add(supplierID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 170, 30));

        voucherDate.setDateFormatString("yyyy-MM-dd");
        voucherDate.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        panel.add(voucherDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 200, 25));

        btn_Cash.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btn_Cash);
        btn_Cash.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Cash.setForeground(new java.awt.Color(66, 73, 73));
        btn_Cash.setText("Cash");
        btn_Cash.setFocusPainted(false);
        btn_Cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CashActionPerformed(evt);
            }
        });
        panel.add(btn_Cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 70, -1));

        btn_Cheque.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btn_Cheque);
        btn_Cheque.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btn_Cheque.setForeground(new java.awt.Color(66, 73, 73));
        btn_Cheque.setText("Cheque");
        btn_Cheque.setFocusPainted(false);
        btn_Cheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChequeActionPerformed(evt);
            }
        });
        panel.add(btn_Cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 80, -1));

        table.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "GRN No", "GRN Date", "GRN Value", "Paid Amount", "Payble"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table.setRowHeight(25);
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(30);
            table.getColumnModel().getColumn(1).setPreferredWidth(250);
            table.getColumnModel().getColumn(2).setPreferredWidth(200);
            table.getColumnModel().getColumn(3).setPreferredWidth(200);
            table.getColumnModel().getColumn(4).setPreferredWidth(200);
            table.getColumnModel().getColumn(5).setPreferredWidth(200);
        }

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 1080, 260));

        btn_Previous.setBackground(new java.awt.Color(204, 204, 204));
        btn_Previous.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Previous.setText("Previous");
        btn_Previous.setBorder(null);
        btn_Previous.setBorderPainted(false);
        btn_Previous.setContentAreaFilled(false);
        btn_Previous.setFocusPainted(false);
        btn_Previous.setOpaque(true);
        btn_Previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_PreviousMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_PreviousMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_PreviousMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_PreviousMouseReleased(evt);
            }
        });
        btn_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PreviousActionPerformed(evt);
            }
        });
        panel.add(btn_Previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, 90, 30));

        btn_Cancel.setBackground(new java.awt.Color(179, 182, 183));
        btn_Cancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Cancel.setText("Cancel");
        btn_Cancel.setBorder(null);
        btn_Cancel.setBorderPainted(false);
        btn_Cancel.setContentAreaFilled(false);
        btn_Cancel.setFocusPainted(false);
        btn_Cancel.setOpaque(true);
        btn_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_CancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_CancelMouseReleased(evt);
            }
        });
        panel.add(btn_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 670, 90, 30));

        btn_Save.setBackground(new java.awt.Color(41, 128, 185));
        btn_Save.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Save.setForeground(new java.awt.Color(255, 255, 255));
        btn_Save.setText("Save");
        btn_Save.setBorder(null);
        btn_Save.setBorderPainted(false);
        btn_Save.setContentAreaFilled(false);
        btn_Save.setFocusPainted(false);
        btn_Save.setOpaque(true);
        btn_Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SaveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_SaveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_SaveMouseReleased(evt);
            }
        });
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });
        panel.add(btn_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 670, 90, 30));

        payMethod.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(66, 73, 73));
        jLabel9.setText("Bank");

        label33.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        label33.setForeground(new java.awt.Color(66, 73, 73));
        label33.setText("Cheque No");

        txt_ChqNo.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txt_ChqNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ChqNoKeyTyped(evt);
            }
        });

        txt_ChqDate.setDateFormatString("yyyy-MM-dd");
        txt_ChqDate.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        label44.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        label44.setForeground(new java.awt.Color(66, 73, 73));
        label44.setText("Cheque Date");

        txt_bankName.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        javax.swing.GroupLayout payMethodLayout = new javax.swing.GroupLayout(payMethod);
        payMethod.setLayout(payMethodLayout);
        payMethodLayout.setHorizontalGroup(
            payMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payMethodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label44, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(payMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ChqDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ChqNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bankName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        payMethodLayout.setVerticalGroup(
            payMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payMethodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bankName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(payMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ChqNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(payMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label44, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ChqDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panel.add(payMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 320, 140));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 73, 94));
        jLabel7.setText("Supplier Payments");
        panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 360, 50));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(66, 73, 73));
        jLabel10.setText("Voucher No");
        panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 25));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/find.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 30, 30));

        supplierName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        supplierName.setForeground(new java.awt.Color(66, 73, 73));
        panel.add(supplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 270, 25));

        voucherValue.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        voucherValue.setForeground(new java.awt.Color(0, 0, 102));
        voucherValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        voucherValue.setText("0,000.00");
        panel.add(voucherValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 620, 180, 25));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel11.setText("Total Voucher Value");
        panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 150, 25));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(66, 73, 73));
        jLabel12.setText("Payment Method");
        panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1166, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PreviousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PreviousMouseEntered
        btn_Previous.setBackground(new Color(179, 182, 183));
    }//GEN-LAST:event_btn_PreviousMouseEntered

    private void btn_PreviousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PreviousMouseExited
        btn_Previous.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btn_PreviousMouseExited

    private void btn_PreviousMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PreviousMousePressed
        btn_Previous.setBackground(new Color(123, 125, 125));
    }//GEN-LAST:event_btn_PreviousMousePressed

    private void btn_PreviousMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PreviousMouseReleased
        btn_Previous.setBackground(new Color(179, 182, 183));
    }//GEN-LAST:event_btn_PreviousMouseReleased

    private void btn_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseEntered
        btn_Cancel.setBackground(new Color(144, 148, 151));
    }//GEN-LAST:event_btn_CancelMouseEntered

    private void btn_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseExited
        btn_Cancel.setBackground(new Color(179, 182, 183));
    }//GEN-LAST:event_btn_CancelMouseExited

    private void btn_CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMousePressed
        btn_Cancel.setBackground(new Color(98, 101, 103));
    }//GEN-LAST:event_btn_CancelMousePressed

    private void btn_CancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseReleased
        btn_Cancel.setBackground(new Color(144, 148, 151));
    }//GEN-LAST:event_btn_CancelMouseReleased

    private void btn_SaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveMouseEntered
        btn_Save.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_SaveMouseEntered

    private void btn_SaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveMouseExited
        btn_Save.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_btn_SaveMouseExited

    private void btn_SaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveMousePressed
        btn_Save.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_btn_SaveMousePressed

    private void btn_SaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveMouseReleased
        btn_Save.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btn_SaveMouseReleased

    private void btn_ChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChequeActionPerformed
        if (btn_Cheque.isSelected()) {
            payMethod.setVisible(true);
        } else {
            payMethod.setVisible(false);
        }
    }//GEN-LAST:event_btn_ChequeActionPerformed

    private void btn_CashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CashActionPerformed
        if (btn_Cash.isSelected()) {
            payMethod.setVisible(false);
        } else {
            payMethod.setVisible(true);
        }
    }//GEN-LAST:event_btn_CashActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SearchSupplier s = new SearchSupplier(menu, this);
        s.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyReleased
        calculateTotal();
    }//GEN-LAST:event_tableKeyReleased

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        if (voucherDate.getDate() == null) {
            JOptionPane.showConfirmDialog(this, "Select a date before save", "Select Date", JOptionPane.WARNING_MESSAGE);
        } else {
            if (supplierID.getText().isEmpty()) {
                JOptionPane.showConfirmDialog(this, "Choose a Supplier before Save", "Select Supplier", JOptionPane.WARNING_MESSAGE);
            } else {
                if (!(btn_Cheque.isSelected() | btn_Cash.isSelected())) {
                    JOptionPane.showConfirmDialog(this, "Select the payment method before save", "Select Payment Method ", JOptionPane.WARNING_MESSAGE);
                } else {
                    if (btn_Cheque.isSelected()) {
                        if (btn_Cheque.getText().isEmpty() | txt_bankName.getText().isEmpty() | txt_ChqDate.getDate() == null) {
                            JOptionPane.showConfirmDialog(this, "Check it again, Please enter the cheque details", "Complete cheque details", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    DefaultTableModel dtm = (DefaultTableModel) table.getModel();
                    calculateTotal();
                    String payMethod;
                    if (btn_Cheque.isSelected()) {
                        payMethod = "Cheque";
                    } else {
                        payMethod = "Cash";
                    }

                    try {
                        DB.iud("INSERT INTO supplier_payment (id_payment, id_supplier, date, value, payment_method) VALUES('" + voucherNo.getText() + "', '" + supplierID.getText() + "', '" + dateFomrmat.format(voucherDate.getDate()) + "','" + voucherValue.getText() + "','" + payMethod + "')");
                        if (btn_Cheque.isSelected()) {
                            DB.iud("INSERT INTO cheque_payment (id_payment, bank, chq_no, chq_date) VALUES('" + voucherNo.getText() + "','" + txt_bankName.getText() + "','" + txt_ChqNo.getText() + "','" + dateFomrmat.format(txt_ChqDate.getDate()) + "')");
                        }
                        for (int i = 0; i < table.getRowCount(); i++) {
                            double payAmount = Double.parseDouble(table.getValueAt(i, 5).toString());

                            if (payAmount != 0) {
                                DB.iud("INSERT INTO payment_items (id_payment,id_grn,paid_amount) VALUES ('" + voucherNo.getText() + "','" + dtm.getValueAt(i, 1).toString() + "','" + payAmount + "')");
                                DB.iud("UPDATE payble_grn SET paid_amount = paid_amount + '" + payAmount + "' WHERE grn_no = '" + dtm.getValueAt(i, 1).toString() + "' ");
                            }

                        }
                        new Save().setVisible(true);
                        clearAllData();
                        generateID();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }
            }
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void txt_ChqNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ChqNoKeyTyped
        Validation.setDigitsOnly(evt);
        Validation.setLength(evt, txt_ChqNo.getText(), 8);
    }//GEN-LAST:event_txt_ChqNoKeyTyped

    private void btn_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PreviousActionPerformed
        try {
            ResultSet rs = DB.search("SELECT supplier_payment.id_payment FROM supplier_payment ORDER BY supplier_payment.id_payment DESC LIMIT 1 ");
            if (rs.next()) {
                SupplierPaymentsView pay = new SupplierPaymentsView(menu, user_Type, rs.getString(1));
                menu.view.removeAll();
                menu.view.revalidate();
                menu.view.repaint();
                menu.view.add((JPanel) pay.panel);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_PreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier_Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JRadioButton btn_Cash;
    private javax.swing.JRadioButton btn_Cheque;
    private javax.swing.JButton btn_Previous;
    private javax.swing.JButton btn_Save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label33;
    private javax.swing.JLabel label44;
    public javax.swing.JPanel panel;
    private javax.swing.JPanel payMethod;
    private javax.swing.JTextField supplierID;
    private javax.swing.JLabel supplierName;
    private javax.swing.JTable table;
    private com.toedter.calendar.JDateChooser txt_ChqDate;
    private javax.swing.JTextField txt_ChqNo;
    private javax.swing.JTextField txt_bankName;
    private com.toedter.calendar.JDateChooser voucherDate;
    private javax.swing.JLabel voucherNo;
    private javax.swing.JLabel voucherValue;
    // End of variables declaration//GEN-END:variables

    private void tableSettings() {
        JTableHeader tableHeader = table.getTableHeader();
        tableHeader.setFont(new Font("Calibri", Font.BOLD, 14));
        ((DefaultTableCellRenderer) tableHeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);

        DefaultTableCellRenderer right = new DefaultTableCellRenderer();
        right.setHorizontalAlignment(JLabel.RIGHT);

        table.getColumnModel().getColumn(0).setCellRenderer(center);
        table.getColumnModel().getColumn(2).setCellRenderer(center);
        table.getColumnModel().getColumn(3).setCellRenderer(right);
        table.getColumnModel().getColumn(4).setCellRenderer(right);
        table.getColumnModel().getColumn(5).setCellRenderer(right);
    }

    private void generateID() {
        try {
            ResultSet rs = DB.search("SELECT COUNT(id_payment) AS id FROM supplier_payment");
            if (rs.next()) {
                int rowcount = rs.getInt("id");
                rowcount++;
                voucherNo.setText("ITP" + String.format("%0" + 7 + "d", rowcount));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadTableData(String id) {
        try {
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            ResultSet rs = DB.search("SELECT grn_no, `date`, `value`, paid_amount, balance FROM payble_payments WHERE payble_payments.id_supplier = '" + id + "' ");
            dtm.setRowCount(0);
            int x = 0;
            while (rs.next()) {
                Vector v = new Vector();
                v.add(++x);
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(decimalformat.format(rs.getDouble(3)));
                v.add(decimalformat.format(rs.getDouble(4)));
                v.add(decimalformat.format(rs.getDouble(5)));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setSupplierData(String ID, String name) {
        supplierID.setText(ID);
        supplierName.setText(name.trim());
        loadTableData(ID);
    }

    private void calculateTotal() {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        double v = 0;
        for (int i = 0; i < table.getRowCount(); i++) {
            v += Double.parseDouble(dtm.getValueAt(i, 5).toString());
        }
        voucherValue.setText(decimalformat.format(v));
    }

    private void clearAllData() {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        supplierID.setText(null);
        supplierName.setText(null);
        btn_Cheque.setSelected(false);
        btn_Cash.setSelected(false);
        txt_bankName.setText(null);
        txt_ChqNo.setText(null);
        txt_ChqDate.setDate(null);
        voucherDate.setDate(null);
        dtm.setRowCount(0);
        voucherValue.setText("0,000.00");
    }
}
