
package GUI;

import Model.Access_Denied;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class UserPopup extends javax.swing.JFrame {

    private Main menu;
    private String user_Type;

    public UserPopup() {
        initComponents();
    }

    public UserPopup(Main m, String type) {
        this();
        this.menu = m;
        this.user_Type = type;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Emp = new javax.swing.JButton();
        btn_users = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(38, 57, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Emp.setBackground(new java.awt.Color(38, 57, 75));
        btn_Emp.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btn_Emp.setForeground(new java.awt.Color(204, 204, 204));
        btn_Emp.setText("Employees");
        btn_Emp.setBorder(null);
        btn_Emp.setBorderPainted(false);
        btn_Emp.setContentAreaFilled(false);
        btn_Emp.setFocusPainted(false);
        btn_Emp.setOpaque(true);
        btn_Emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_EmpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_EmpMouseReleased(evt);
            }
        });
        btn_Emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 50));

        btn_users.setBackground(new java.awt.Color(38, 57, 75));
        btn_users.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btn_users.setForeground(new java.awt.Color(204, 204, 204));
        btn_users.setText("Users");
        btn_users.setBorder(null);
        btn_users.setBorderPainted(false);
        btn_users.setContentAreaFilled(false);
        btn_users.setFocusPainted(false);
        btn_users.setOpaque(true);
        btn_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_usersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_usersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_usersMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_usersMouseReleased(evt);
            }
        });
        btn_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usersActionPerformed(evt);
            }
        });
        jPanel1.add(btn_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpMouseEntered
        btn_Emp.setBackground(new Color(52, 73, 94));
    }//GEN-LAST:event_btn_EmpMouseEntered

    private void btn_EmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpMouseExited
        btn_Emp.setBackground(new Color(38, 57, 75));
    }//GEN-LAST:event_btn_EmpMouseExited

    private void btn_EmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpMousePressed
        btn_Emp.setForeground(new Color(0, 204, 204));
        btn_Emp.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_btn_EmpMousePressed

    private void btn_EmpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EmpMouseReleased
        btn_Emp.setForeground(new Color(204, 204, 204));
        btn_Emp.setBackground(new Color(52, 73, 94));
    }//GEN-LAST:event_btn_EmpMouseReleased

    private void btn_usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usersMouseEntered
        btn_users.setBackground(new Color(52, 73, 94));
    }//GEN-LAST:event_btn_usersMouseEntered

    private void btn_usersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usersMouseExited
        btn_users.setBackground(new Color(38, 57, 75));
    }//GEN-LAST:event_btn_usersMouseExited

    private void btn_usersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usersMousePressed
        btn_users.setForeground(new Color(0, 204, 204));
        btn_users.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_btn_usersMousePressed

    private void btn_usersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usersMouseReleased
        btn_users.setForeground(new Color(204, 204, 204));
        btn_users.setBackground(new Color(52, 73, 94));
    }//GEN-LAST:event_btn_usersMouseReleased

    private void btn_EmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpActionPerformed

        if (user_Type.equals("Admin")) {
            Employees emp = new Employees(menu, user_Type);
            menu.view.removeAll();
            menu.view.revalidate();
            menu.view.repaint();
            menu.view.add((JPanel) emp.panel);
            this.dispose();

        } else if (user_Type.equals("Manager")) {
            Employees emp = new Employees(menu, user_Type);
            menu.view.removeAll();
            menu.view.revalidate();
            menu.view.repaint();
            menu.view.add((JPanel) emp.panel);
            this.dispose();

        } else if (user_Type.equals("Cashier")) {
            Access_Denied ad = new Access_Denied();
            JOptionPane.showMessageDialog(menu, ad.panel, "Acess Denied", JOptionPane.PLAIN_MESSAGE);

        } else if (user_Type.equals("DataEntry")) {
            Access_Denied ad = new Access_Denied();
            JOptionPane.showMessageDialog(menu, ad.panel, "Acess Denied", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btn_EmpActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        this.dispose();
        System.gc();
    }//GEN-LAST:event_formWindowLostFocus

    private void btn_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usersActionPerformed

        if (user_Type.equals("Admin")) {
            Users user = new Users(menu);
            menu.view.removeAll();
            menu.view.revalidate();
            menu.view.repaint();
            menu.view.add((JPanel) user.panel);
            this.dispose();

        } else if (user_Type.equals("Manager")) {
            Access_Denied ad = new Access_Denied();
            JOptionPane.showMessageDialog(menu, ad.panel, "Acess Denied", JOptionPane.PLAIN_MESSAGE);

        } else if (user_Type.equals("Cashier")) {
            Access_Denied ad = new Access_Denied();
            JOptionPane.showMessageDialog(menu, ad.panel, "Acess Denied", JOptionPane.PLAIN_MESSAGE);

        } else if (user_Type.equals("DataEntry")) {
            Access_Denied ad = new Access_Denied();
            JOptionPane.showMessageDialog(menu, ad.panel, "Acess Denied", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btn_usersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Emp;
    private javax.swing.JButton btn_users;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
